import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared-components/layout/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen divide-x">
          <div className="px-4 py-4 ">
            <Sidebar />
          </div>
          <div className="w-full h-full overflow-scroll overflow-x-hidden px-4 py-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
